disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - implicit_getter
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Tests